@startuml
title MasterMind
skinparam style strictuml
skinparam shadowing false
skinparam nodesep 100
skinparam ranksep 100

Mastermind *-down-> "2" Player
Mastermind *-down-> "2" Turn
Mastermind *-down-> Board

Turn -down-> Player

Player <|-down- CodeMaker
Player <|-down- CodeBreaker

Board *-down->SecretPattern
Board o-down->"0..12"ProposedPattern

Pattern <|-down- ProposedPattern
Pattern <|-down- SecretPattern

CodeMaker -down-> SecretPattern
CodeMaker -down-> Score
CodeBreaker -down-> ProposedPattern


CorrectPattern *-down-> ProposedPattern
CorrectPattern -down-> SecretPattern

ProposedPattern *-down->"4"CodePeg
CorrectPattern *-down->"4"KeyPeg
SecretPattern *-down->"4"CodePeg

ProposedPattern -down-> Score

CodePeg -down->Position
Peg <|-down- KeyPeg
Peg <|-down- CodePeg

note bottom of KeyPeg
 <size:9><i>Black:Correct color & position</i></size>
 <size:9><i>White:Correct color bad position</i></size>
end note

note bottom of CodePeg
 <size:9><i>6 colors</i></size>
end note

@enduml
